FROM mhart/alpine-node:4
RUN npm install -g coffee-script twerp supervisor
RUN apk add --update alpine-sdk python python-dev
WORKDIR /apiaxle/api
ADD base /apiaxle/base
ADD api /apiaxle/api
RUN npm install libxmljs && make link && npm install && make clean && make
RUN apk del --purge alpine-sdk python python-dev
VOLUME /apiaxle/api
CMD NODE_ENV=production supervisor --force-watch -x coffee -w "lib,app,/apiaxle/base/lib,/apiaxle/base/app" -- ./apiaxle-api.coffee -h 0.0.0.0 -p 3100 -f 1
